In [3]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('iris.csv')
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
capital=lambda x:x.upper()

df['Species'].apply(capital)

0         IRIS-SETOSA
1         IRIS-SETOSA
2         IRIS-SETOSA
3         IRIS-SETOSA
4         IRIS-SETOSA
5         IRIS-SETOSA
6         IRIS-SETOSA
7         IRIS-SETOSA
8         IRIS-SETOSA
9         IRIS-SETOSA
10        IRIS-SETOSA
11        IRIS-SETOSA
12        IRIS-SETOSA
13        IRIS-SETOSA
14        IRIS-SETOSA
15        IRIS-SETOSA
16        IRIS-SETOSA
17        IRIS-SETOSA
18        IRIS-SETOSA
19        IRIS-SETOSA
20        IRIS-SETOSA
21        IRIS-SETOSA
22        IRIS-SETOSA
23        IRIS-SETOSA
24        IRIS-SETOSA
25        IRIS-SETOSA
26        IRIS-SETOSA
27        IRIS-SETOSA
28        IRIS-SETOSA
29        IRIS-SETOSA
            ...
120    IRIS-VIRGINICA
121    IRIS-VIRGINICA
122    IRIS-VIRGINICA
123    IRIS-VIRGINICA
124    IRIS-VIRGINICA
125    IRIS-VIRGINICA
126    IRIS-VIRGINICA
127    IRIS-VIRGINICA
128    IRIS-VIRGINICA
129    IRIS-VIRGINICA
130    IRIS-VIRGINICA
131    IRIS-VIRGINICA
132    IRIS-VIRGINICA
133    IRIS-VIRGINICA
134    IRIS-VIRGINICA
135    IRIS-VIRGINICA
136    IRIS-VIRGINICA
137    IRIS-VIRGINICA
138    IRIS-VIRGINICA
139    IRIS-VIRGINICA
140    IRIS-VIRGINICA
141    IRIS-VIRGINICA
142    IRIS-VIRGINICA
143    IRIS-VIRGINICA
144    IRIS-VIRGINICA
145    IRIS-VIRGINICA
146    IRIS-VIRGINICA
147    IRIS-VIRGINICA
148    IRIS-VIRGINICA
149    IRIS-VIRGINICA
Name: Species, Length: 150, dtype: object

In [5]:
df['Species']

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
5         Iris-setosa
6         Iris-setosa
7         Iris-setosa
8         Iris-setosa
9         Iris-setosa
10        Iris-setosa
11        Iris-setosa
12        Iris-setosa
13        Iris-setosa
14        Iris-setosa
15        Iris-setosa
16        Iris-setosa
17        Iris-setosa
18        Iris-setosa
19        Iris-setosa
20        Iris-setosa
21        Iris-setosa
22        Iris-setosa
23        Iris-setosa
24        Iris-setosa
25        Iris-setosa
26        Iris-setosa
27        Iris-setosa
28        Iris-setosa
29        Iris-setosa
            ...
120    Iris-virginica
121    Iris-virginica
122    Iris-virginica
123    Iris-virginica
124    Iris-virginica
125    Iris-virginica
126    Iris-virginica
127    Iris-virginica
128    Iris-virginica
129    Iris-virginica
130    Iris-virginica
131    Iris-virginica
132    Iris-virginica
133    Iris-virginica
134    Iris-virginica
135    Iris-virginica
136    Iris-virginica
137    Iris-virginica
138    Iris-virginica
139    Iris-virginica
140    Iris-virginica
141    Iris-virginica
142    Iris-virginica
143    Iris-virginica
144    Iris-virginica
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Species, Length: 150, dtype: object

In [7]:
#map  function 
df['Species'].map(capital)

0         IRIS-SETOSA
1         IRIS-SETOSA
2         IRIS-SETOSA
3         IRIS-SETOSA
4         IRIS-SETOSA
5         IRIS-SETOSA
6         IRIS-SETOSA
7         IRIS-SETOSA
8         IRIS-SETOSA
9         IRIS-SETOSA
10        IRIS-SETOSA
11        IRIS-SETOSA
12        IRIS-SETOSA
13        IRIS-SETOSA
14        IRIS-SETOSA
15        IRIS-SETOSA
16        IRIS-SETOSA
17        IRIS-SETOSA
18        IRIS-SETOSA
19        IRIS-SETOSA
20        IRIS-SETOSA
21        IRIS-SETOSA
22        IRIS-SETOSA
23        IRIS-SETOSA
24        IRIS-SETOSA
25        IRIS-SETOSA
26        IRIS-SETOSA
27        IRIS-SETOSA
28        IRIS-SETOSA
29        IRIS-SETOSA
            ...
120    IRIS-VIRGINICA
121    IRIS-VIRGINICA
122    IRIS-VIRGINICA
123    IRIS-VIRGINICA
124    IRIS-VIRGINICA
125    IRIS-VIRGINICA
126    IRIS-VIRGINICA
127    IRIS-VIRGINICA
128    IRIS-VIRGINICA
129    IRIS-VIRGINICA
130    IRIS-VIRGINICA
131    IRIS-VIRGINICA
132    IRIS-VIRGINICA
133    IRIS-VIRGINICA
134    IRIS-VIRGINICA
135    IRIS-VIRGINICA
136    IRIS-VIRGINICA
137    IRIS-VIRGINICA
138    IRIS-VIRGINICA
139    IRIS-VIRGINICA
140    IRIS-VIRGINICA
141    IRIS-VIRGINICA
142    IRIS-VIRGINICA
143    IRIS-VIRGINICA
144    IRIS-VIRGINICA
145    IRIS-VIRGINICA
146    IRIS-VIRGINICA
147    IRIS-VIRGINICA
148    IRIS-VIRGINICA
149    IRIS-VIRGINICA
Name: Species, Length: 150, dtype: object

In [8]:
#Dropping unwanted columns
df = df.drop(['Id','Species'], axis=1)
df.head()

   SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [9]:
#ApplyMap function usage on Built-In function (sqrt, square)
df.applymap(np.sqrt)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0         2.258318      1.870829       1.183216      0.447214
1         2.213594      1.732051       1.183216      0.447214
2         2.167948      1.788854       1.140175      0.447214
3         2.144761      1.760682       1.224745      0.447214
4         2.236068      1.897367       1.183216      0.447214
5         2.323790      1.974842       1.303840      0.632456
6         2.144761      1.843909       1.183216      0.547723
7         2.236068      1.843909       1.224745      0.447214
8         2.097618      1.702939       1.183216      0.447214
9         2.213594      1.760682       1.224745      0.316228
10        2.323790      1.923538       1.224745      0.447214
11        2.190890      1.843909       1.264911      0.447214
12        2.190890      1.732051       1.183216      0.316228
13        2.073644      1.732051       1.048809      0.316228
14        2.408319      2.000000       1.095445      0.447214
15        2.387467      2.097618       1.224745      0.632456
16        2.323790      1.974842       1.140175      0.632456
17        2.258318      1.870829       1.183216      0.547723
18        2.387467      1.949359       1.303840      0.547723
19        2.258318      1.949359       1.224745      0.547723
20        2.323790      1.843909       1.303840      0.447214
21        2.258318      1.923538       1.224745      0.632456
22        2.144761      1.897367       1.000000      0.447214
23        2.258318      1.816590       1.303840      0.707107
24        2.190890      1.843909       1.378405      0.447214
25        2.236068      1.732051       1.264911      0.447214
26        2.236068      1.843909       1.264911      0.632456
27        2.280351      1.870829       1.224745      0.447214
28        2.280351      1.843909       1.183216      0.447214
29        2.167948      1.788854       1.264911      0.447214
..             ...           ...            ...           ...
120       2.626785      1.788854       2.387467      1.516575
121       2.366432      1.673320       2.213594      1.414214
122       2.774887      1.673320       2.588436      1.414214
123       2.509980      1.643168       2.213594      1.341641
124       2.588436      1.816590       2.387467      1.449138
125       2.683282      1.788854       2.449490      1.341641
126       2.489980      1.673320       2.190890      1.341641
127       2.469818      1.732051       2.213594      1.341641
128       2.529822      1.673320       2.366432      1.449138
129       2.683282      1.732051       2.408319      1.264911
130       2.720294      1.673320       2.469818      1.378405
131       2.810694      1.949359       2.529822      1.414214
132       2.529822      1.673320       2.366432      1.483240
133       2.509980      1.673320       2.258318      1.224745
134       2.469818      1.612452       2.366432      1.183216
135       2.774887      1.732051       2.469818      1.516575
136       2.509980      1.843909       2.366432      1.549193
137       2.529822      1.760682       2.345208      1.341641
138       2.449490      1.732051       2.190890      1.341641
139       2.626785      1.760682       2.323790      1.449138
140       2.588436      1.760682       2.366432      1.549193
141       2.626785      1.760682       2.258318      1.516575
142       2.408319      1.643168       2.258318      1.378405
143       2.607681      1.788854       2.428992      1.516575
144       2.588436      1.816590       2.387467      1.581139
145       2.588436      1.732051       2.280351      1.516575
146       2.509980      1.581139       2.236068      1.378405
147       2.549510      1.732051       2.280351      1.414214
148       2.489980      1.843909       2.323790      1.516575
149       2.428992      1.732051       2.258318      1.341641

[150 rows x 4 columns]

In [10]:
df.applymap(np.square)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            26.01         12.25           1.96          0.04
1            24.01          9.00           1.96          0.04
2            22.09         10.24           1.69          0.04
3            21.16          9.61           2.25          0.04
4            25.00         12.96           1.96          0.04
5            29.16         15.21           2.89          0.16
6            21.16         11.56           1.96          0.09
7            25.00         11.56           2.25          0.04
8            19.36          8.41           1.96          0.04
9            24.01          9.61           2.25          0.01
10           29.16         13.69           2.25          0.04
11           23.04         11.56           2.56          0.04
12           23.04          9.00           1.96          0.01
13           18.49          9.00           1.21          0.01
14           33.64         16.00           1.44          0.04
15           32.49         19.36           2.25          0.16
16           29.16         15.21           1.69          0.16
17           26.01         12.25           1.96          0.09
18           32.49         14.44           2.89          0.09
19           26.01         14.44           2.25          0.09
20           29.16         11.56           2.89          0.04
21           26.01         13.69           2.25          0.16
22           21.16         12.96           1.00          0.04
23           26.01         10.89           2.89          0.25
24           23.04         11.56           3.61          0.04
25           25.00          9.00           2.56          0.04
26           25.00         11.56           2.56          0.16
27           27.04         12.25           2.25          0.04
28           27.04         11.56           1.96          0.04
29           22.09         10.24           2.56          0.04
..             ...           ...            ...           ...
120          47.61         10.24          32.49          5.29
121          31.36          7.84          24.01          4.00
122          59.29          7.84          44.89          4.00
123          39.69          7.29          24.01          3.24
124          44.89         10.89          32.49          4.41
125          51.84         10.24          36.00          3.24
126          38.44          7.84          23.04          3.24
127          37.21          9.00          24.01          3.24
128          40.96          7.84          31.36          4.41
129          51.84          9.00          33.64          2.56
130          54.76          7.84          37.21          3.61
131          62.41         14.44          40.96          4.00
132          40.96          7.84          31.36          4.84
133          39.69          7.84          26.01          2.25
134          37.21          6.76          31.36          1.96
135          59.29          9.00          37.21          5.29
136          39.69         11.56          31.36          5.76
137          40.96          9.61          30.25          3.24
138          36.00          9.00          23.04          3.24
139          47.61          9.61          29.16          4.41
140          44.89          9.61          31.36          5.76
141          47.61          9.61          26.01          5.29
142          33.64          7.29          26.01          3.61
143          46.24         10.24          34.81          5.29
144          44.89         10.89          32.49          6.25
145          44.89          9.00          27.04          5.29
146          39.69          6.25          25.00          3.61
147          42.25          9.00          27.04          4.00
148          38.44         11.56          29.16          5.29
149          34.81          9.00          26.01          3.24

[150 rows x 4 columns]

In [11]:
def multiply50(x):
    if type(x) is str:
        return x
    else:
        return 50*x

In [12]:

df.applymap(multiply50)

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            255.0         175.0           70.0          10.0
1            245.0         150.0           70.0          10.0
2            235.0         160.0           65.0          10.0
3            230.0         155.0           75.0          10.0
4            250.0         180.0           70.0          10.0
5            270.0         195.0           85.0          20.0
6            230.0         170.0           70.0          15.0
7            250.0         170.0           75.0          10.0
8            220.0         145.0           70.0          10.0
9            245.0         155.0           75.0           5.0
10           270.0         185.0           75.0          10.0
11           240.0         170.0           80.0          10.0
12           240.0         150.0           70.0           5.0
13           215.0         150.0           55.0           5.0
14           290.0         200.0           60.0          10.0
15           285.0         220.0           75.0          20.0
16           270.0         195.0           65.0          20.0
17           255.0         175.0           70.0          15.0
18           285.0         190.0           85.0          15.0
19           255.0         190.0           75.0          15.0
20           270.0         170.0           85.0          10.0
21           255.0         185.0           75.0          20.0
22           230.0         180.0           50.0          10.0
23           255.0         165.0           85.0          25.0
24           240.0         170.0           95.0          10.0
25           250.0         150.0           80.0          10.0
26           250.0         170.0           80.0          20.0
27           260.0         175.0           75.0          10.0
28           260.0         170.0           70.0          10.0
29           235.0         160.0           80.0          10.0
..             ...           ...            ...           ...
120          345.0         160.0          285.0         115.0
121          280.0         140.0          245.0         100.0
122          385.0         140.0          335.0         100.0
123          315.0         135.0          245.0          90.0
124          335.0         165.0          285.0         105.0
125          360.0         160.0          300.0          90.0
126          310.0         140.0          240.0          90.0
127          305.0         150.0          245.0          90.0
128          320.0         140.0          280.0         105.0
129          360.0         150.0          290.0          80.0
130          370.0         140.0          305.0          95.0
131          395.0         190.0          320.0         100.0
132          320.0         140.0          280.0         110.0
133          315.0         140.0          255.0          75.0
134          305.0         130.0          280.0          70.0
135          385.0         150.0          305.0         115.0
136          315.0         170.0          280.0         120.0
137          320.0         155.0          275.0          90.0
138          300.0         150.0          240.0          90.0
139          345.0         155.0          270.0         105.0
140          335.0         155.0          280.0         120.0
141          345.0         155.0          255.0         115.0
142          290.0         135.0          255.0          95.0
143          340.0         160.0          295.0         115.0
144          335.0         165.0          285.0         125.0
145          335.0         150.0          260.0         115.0
146          315.0         125.0          250.0          95.0
147          325.0         150.0          260.0         100.0
148          310.0         170.0          270.0         115.0
149          295.0         150.0          255.0          90.0

[150 rows x 4 columns]

In [1]:
dataf['Emp_name']=dataf['data'].str.extract('(([A-Z])\w+)',expand = True)
dataf['Emp_name']

NameError: name 'dataf' is not defined